version: '3'

tasks:
  default:
    cmds:
    - task: install

  install:
    desc: Install dependencies
    sources:
      - package.json
    generates:
      - bun.lock
    cmds:
      - bun install --frozen-lockfile

  build:
    desc: Build GitHub Action
    deps:
      - install
    sources:
      - src/**/*.ts
    generates:
      - dist/index.js
    cmds:
      - bun run build.ts

  test:
    desc: Run unit tests
    cmds:
      - bun test {{ .CLI_ARGS }}

  test:watch:
    desc: Run tests in watch mode
    cmd:
      task: test
      vars:
        CLI_ARGS: --watch
