# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default:
    desc: Same as `task install`
    cmds:
    - task: install

  pull:
    desc: Pull latest changes from VCS
    cmd: git pull --rebase --force

  install:
    desc: Install dependencies
    run: once
    sources:
      - package.json
    generates:
      - bun.lock
    cmds:
      - bun install --frozen-lockfile
      - bun audit --audit-level=low

  build:
    desc: Build GitHub Action
    deps: [docs]
    sources:
      - bin/**/*.ts
      - src/**/*.ts
    generates:
      - dist/index.js
    cmd: >
        bun build bin/index.ts
        --production
        --target node
        --outdir dist
        --format esm

  clean:
    desc: Cleans and rebuilds artifacts
    cmds:
      - rm -rf dist/
      - task: build

  test:
    desc: Run the whole test suite
    cmds:
      - task: test:unit
      - task: test:mutation
      - task: test:build

  test:unit:
    desc: Run unit tests
    deps: [install]
    cmd: bun test --coverage {{ .CLI_ARGS }}

  test:watch:
    desc: Run tests in watch mode
    deps: [install]
    cmd:
      task: test:unit
      vars:
        CLI_ARGS: --watch

  test:mutation:
    desc: Run mutation tests with StrykerJS
    deps: [install]
    cmd: bunx stryker run

  test:build:
    desc: Run post-build test
    deps: [build]
    dir: dist
    cmd: node index.js
    env:
      INPUT_STRING: Hello, world!

  lint:
    desc: Lint the codebase
    deps: [install]
    cmds:
      - actionlint
      - bunx @biomejs/biome check .

  format:
    desc: Format code with Biome
    deps: [install]
    cmd: bunx @biomejs/biome check --write .

  docs:
    desc: Update documentation
    deps: [install]
    sources:
      - action.yml
    generates:
      - README.md
    cmd: bunx action-docs --no-banner --update-readme
