version: '3'

tasks:
  default:
    cmds:
    - task: install

  pull:
    desc: Pull latest changes from VCS
    cmd: git pull --rebase --force

  install:
    desc: Install dependencies
    sources:
      - package.json
    generates:
      - bun.lock
    cmd: bun install --frozen-lockfile

  build:
    desc: Build GitHub Action
    sources:
      - bin/**/*.ts
      - src/**/*.ts
    generates:
      - dist/index.js
    cmd: >
        bun build bin/index.ts
        --production
        --target node
        --outdir dist
        --format esm

  clean:
    desc: Clean build artifacts
    cmd: rm -rf dist/

  test:
    desc: Run the whole test suite
    cmds:
      - task: test:unit
      - task: test:mutation
      - task: test:build

  test:unit:
    desc: Run unit tests
    cmd: bun test --coverage {{ .CLI_ARGS }}

  test:watch:
    desc: Run tests in watch mode
    cmd:
      task: test:unit
      vars:
        CLI_ARGS: --watch

  test:mutation:
    desc: Run mutation tests with StrykerJS
    cmd: bunx stryker run

  test:build:
    desc: Run post-build test
    deps: [build]
    dir: dist
    cmd: node index.js
    env:
      INPUT_STRING: Hello, world!

  lint:
    desc: Lint code with Biome
    cmd: bunx @biomejs/biome check .

  format:
    desc: Format code with Biome
    cmd: bunx @biomejs/biome check --write .
