version: '3'

tasks:
  default:
    cmds:
    - task: install

  pull:
    desc: Pull latest changes from VCS
    cmds:
      - git pull --rebase --force

  install:
    desc: Install dependencies
    deps:
      - pull
    sources:
      - package.json
    generates:
      - bun.lock
    cmds:
      - bun install --frozen-lockfile

  build:
    desc: Build GitHub Action
    sources:
      - src/**/*.ts
    generates:
      - dist/index.js
    cmds:
      - >
        bun build src/index.ts
        --production
        --target node
        --outdir dist
        --format esm

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/

  test:
    desc: Run unit tests
    cmds:
      - bun test {{ .CLI_ARGS }}

  test:watch:
    desc: Run tests in watch mode
    cmd:
      task: test
      vars:
        CLI_ARGS: --watch

  lint:
    desc: Lint code with Biome
    cmds:
      - bunx @biomejs/biome check .

  format:
    desc: Format code with Biome
    cmds:
      - bunx @biomejs/biome check --write .
