name: Acceptance Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.22

      - name: Install Task
        uses: go-task/setup-task@v1
        with:
          repo-token: ${{ github.token }}
          version: '3.x'

      - name: Install dependencies
        run: task install

      - name: Run unit tests
        run: task test

      - name: Build application
        run: task build

  test-action:
    name: Action Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Greet user
        uses: ./
        id: hello
        with:
          who-to-greet: Niko

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
