name: Acceptance Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  original: "Hello, World!"
  transformed: "Uryyb, Jbeyq!"

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1

      - name: Install Task
        uses: go-task/setup-task@v1
        with:
          repo-token: ${{ github.token }}
          version: '3.x'

      - name: Install dependencies
        run: task install

      - name: Build action
        run: task build

      - name: Ensure action build is current
        run: |
          if ! git diff --exit-code --name-only; then
            echo "::error::Files were mutated during build. Run 'task build' before committing and pushing."
            exit 1
          fi

      - name: Lint code
        run: task lint

      - name: Run tests
        run: task test

  test-local-action:
    name: Test local action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: ROT-13
        uses: ./
        id: rot13
        with:
          string: ${{ env.original }}

      - name: Fail expectation
        if: steps.rot13.outputs.result != env.transformed
        run: |
          echo "::error::Expected result of transformation was '${{ env.transformed }}', but got '${{ steps.rot13.outputs.result }}'"
          exit 1

  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test-unit, test-local-action]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Determine next version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          create_annotated_tag: true
          dry_run: true
          tag_prefix: ""

      - name: Create and push version tags
        if: steps.tag_version.outputs.new_tag != steps.tag_version.outputs.previous_tag
        run: |
          VERSION="${{ steps.tag_version.outputs.new_version }}"
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f1-2)
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -a "$VERSION" -m "Release $VERSION"
          git tag -fa "v$MAJOR" -m "Release v$MAJOR"
          git tag -fa "v$MINOR" -m "Release v$MINOR"
          
          git push origin "$VERSION"
          git push origin "v$MAJOR" --force
          git push origin "v$MINOR" --force

      - name: Create GitHub release
        if: steps.tag_version.outputs.new_tag != steps.tag_version.outputs.previous_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.tag_version.outputs.new_version }}" \
            --title "Release ${{ steps.tag_version.outputs.new_version }}" \
            --generate-notes

  test-tagged-action:
    name: Test tagged action
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: ROT-13
        uses: nikoheikkila/rot-13-action@v1
        id: rot13
        with:
          string: ${{ env.original }}

      - name: Fail expectation
        if: steps.rot13.outputs.result != env.transformed
        run: |
          echo "::error::Expected result of transformation was '${{ env.transformed }}', but got '${{ steps.rot13.outputs.result }}'"
          exit 1
